server:
  port: 6969
  servlet:
      context-path: /quartz
tomcat:
    remote-ip-header: x-forward-for
    uri-encoding: UTF-8
    max-threads: 10
    background-processor-delay: 30
    basedir: ${user.home}/tomcat/
#mybatis-plus配置控制台打印完整带参数SQL语句
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
    banner:
      charset: UTF-8
    http:
      encoding:
        force: true
        charset: UTF-8
    application:
        name: spring-boot-EasyUrlTask
    freemarker:
        request-context-attribute: request
        suffix: .html
        content-type: text/html
        enabled: true
        cache: false
        charset: UTF-8
        allow-request-override: false
        expose-request-attributes: true
        expose-session-attributes: true
        expose-spring-macro-helpers: true
        settings:
          number_format: 0.##
          default_encoding: UTF-8
#          template_loader: /templates/
#    mvc:
#      static-path-pattern: /statics/**
    datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.cj.jdbc.Driver
      platform: mysql
      url: jdbc:mysql://127.0.0.1:3306/quartz?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: root123
      initialSize: 1
      minIdle: 2
      maxActive: 2
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      filters: stat,wall,log4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      # 配置DruidStatFilter
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*,/system/druid/*"
    quartz:
      job-store-type: jdbc
      jobStore:
        class: org.quartz.impl.jdbcjobstore.JobStoreTX
        clusterCheckinInterval: 10000
        driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
        isClustered: true
        tablePrefix: QRTZ_
        useProperties: false
      scheduler:
        instanceId: AUTO
        instanceName: clusteredScheduler
      threadPool:
        class: org.quartz.simpl.SimpleThreadPool
        threadCount: 10
        threadPriority: 5
        threadsInheritContextClassLoaderOfInitializingThread: true

